config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :users

  get "/" => "home#index"
  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#destroy", as: :destroy_session

  post "users/login", to: "users#login"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ActiveRecord::Base
  validates :todo_text, presence: true
  validates :todo_text, length: { minimum: 2 }
  validates :due_date, presence: true
  belongs_to :user

  def self.of_user(user)
    all.where(user_id: user.id)
  end

  def self.due_today
    all.where("due_date = ? ", Date.today).order({ created_at: :desc })
  end

  def self.due_later
    all.where("due_date > ? ", Date.today).order({ created_at: :desc })
  end

  def self.overdue
    all.where("due_date < ? and completed = ? ", Date.today, false).order({ created_at: :desc })
  end

  def self.is_completed
    all.where("completed = ? ", true)
  end
end

app/models/user.rb
class User < ApplicationRecord
  validates :first_name, presence: true
  validates :email, presence: true
  has_secure_password
  has_many :todos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :ensure_logged_in

  def ensure_logged_in
    unless current_user
      redirect_to "/"
    end
  end

  def current_user
    return @current_user if @current_user
    current_user_id = session[:current_user_id]
    if current_user_id
      @current_user = User.find(current_user_id)
    else
      nil
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :ensure_logged_in

  # HOME PAGE
  # Checks for Session and Routes to /todos page
  def index
    if current_user
      redirect_to todos_path
    else
      render "index"
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :ensure_logged_in

  # Renders sessions/new.html.erb
  # New Log-In Page
  def new
  end

  # Log-In Authentication
  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:current_user_id] = user.id
      redirect_to "/"
    else
      flash[:error] = "Invalid Login Attemp Please Retry"
      redirect_to new_sessions_path
    end
  end

  # Destroying the Session
  def destroy
    session[:current_user_id] = nil
    @current_user = nil
    redirect_to "/"
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  def index
    @todos = Todo.of_user(current_user)
    render "index"
  end

  # Saves Todo Based on ActiveRecord Validation from Todo.rb
  # if done => /todos for refresh
  def create
    todo_text = params[:todo_text]
    due_date = params[:due_date]
    new_todo = Todo.new(todo_text: todo_text, due_date: due_date, completed: false, user_id: current_user.id)
    new_todo.save
    if new_todo.save
      redirect_to todos_path
    else
      flash[:error] = new_todo.errors.full_messages.join(" , ")
      redirect_to todos_path
    end
  end

  def update
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    complete = todo.completed
    todo.completed = !complete
    todo.save!
    redirect_to todos_path
  end

  def destroy
    id = params[:id]
    todo = Todo.of_user(current_user).find(id)
    todo.destroy
    redirect_to todos_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :ensure_logged_in

  # Renders users/new.html.erb
  # New Sign-In Page
  def new
    render "users/new"
  end

  # New User Creation
  def create
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    password = params[:password]
    new_user = User.new(first_name: first_name, email: email, password: password, last_name: last_name)
    new_user.save

    if new_user.save
      redirect_to "/"
    else
      flash[:error] = new_user.errors.full_messages.join(" , ")
      redirect_to new_user_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome To Home Page </h1>

<p class="home-text"> New User? <%= link_to "Sign Up Here!", new_user_path %> </p>
<p  class="home-text"> Existing User? <%= link_to "Sign In Here!", new_sessions_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>

  <body class='todo-container'>
    <% if @current_user %>
      <div class='user-header'>
        Welcome Back <%= @current_user.first_name %>!
        <%= link_to "Sign-Out", destroy_session_path, method: "delete" %>
      </div>
    <% end %>

    <% if flash[:error] %>
      <div class='flash-container'>
        <%= flash[:error] %>
      </div>
    <% end %>
    
  
    <%= yield %>
  </body>
</html>

app/views/todos/_todo-section.html.erb
<div class="list-container">
  <h4 class="list-heading"> 
    <%= section_title %>
      <span class="number">
        <%= todos.is_completed.count %>/<%= todos.count %> 
      </span>
  </h4>
  <% todos.each do |todo| %>
    <div class="todo-item">
        <%= form_with(url: "/todos/#{todo.id}", method: "put") do %>
          <input type="checkbox" name='completed' <%= todo.completed ? "checked" : "" %> onclick="this.form.submit()">
        <% end %> 
        <p class='<%= todo.completed ? "strike" : "" %>'> <%= todo.todo_text %> </p>
        <% if show_due_date %>
          <span class='todo-date'> <%= todo.due_date.to_s(:short) %></span>
        <% end %>  
        <%= form_with(url: "/todos/#{todo.id}", method: "delete") do %>  
          <input type="image" src="/delete.svg"  class='trash'>
        <% end %>
    </div>
  <% end %>  
</div>

app/views/todos/index.html.erb
<div class="todo-container">
    <h2>My Todo List</h2>
    <%= form_with(url: "/todos/", method: "POST", class: "input-container") do %>
      <%= text_field_tag "todo_text", nil, placeholder: "Enter a Todo" %>
      <%= text_field_tag "due_date", nil, type: "date" %>
      <input class="btn-add" type='submit' value="Add" />
    <% end %>
    <%= render partial: "todo-section",
               locals: { section_title: "Overdue", todos: @todos.overdue, show_due_date: true } %>
    <%= render partial: "todo-section",
               locals: { section_title: "Due Today", todos: @todos.due_today, show_due_date: false } %>
    <%= render partial: "todo-section",
               locals: { section_title: "Due Later", todos: @todos.due_later, show_due_date: true } %>

</div>

app/views/users/new.html.erb
<h1>Welcome User</h1>
<section class='user-container'>
  <%= form_with url: users_path do |form| %>
<div class='user-form-field'>
    <p class='user-form-label'>First Name: </p>
    <%= form.text_field :first_name %>
  </div>
  <div class='user-form-field'>
    <p class='user-form-label'>Last Name: </p>
    <%= form.text_field :last_name %>
  </div>
  <div class='user-form-field'>
    <p class='user-form-label'>Email: </p>
    <%= form.email_field :email %>
  </div>
  <div class='user-form-field'>
    <p class='user-form-label'>Password:</p>
    <%= form.password_field :password %>
  </div>
  <div class='user-form-field'>
    <%= form.submit "Sign-Up", class: "submit-btn" %>
  </div>
<% end %>
</section>